version: '2.1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
    command: python -m df.hello
    depends_on:
      - postgres
    environment:
      SECRET: "${SECRET}"

  postgres:
    image: postgres:12
    ports:
      - "5432"
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    environment:
      # credentials taken from .env file
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "password"
