version: '2.1'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
    command: python -m df.hello
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - "5432"
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
    environment:
      # credentials taken from .env file
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
